# Using Python for Linear Algebra
Goal: gain some familiarity with using python to do basic matrix operations.  
  
A little familiarity with Python is pretty crucial for students going into engineering and data science. This is meant to be a little introduction for students in Linear Algebra without any previous Python experience.

First off, we import the package we'll need to manipulate matrices. Python is a general purpose coding language, so most specific uses require a library or two. Luckily there are a huge number of libraries to do almost anything. Numpy is a massive library with tools to manipulate large matricies and lists of data. We'll give it the nickname np as we import it so we can type a bit less.

In [2]:
import numpy as np

We'll also define a function that makes our matricies print out a bit better, don't worry about how this works. It's just for formatting.

In [23]:
def pretty(self):
    pretty_version = ""
    # add all but last rows to return string with newlines
    for row in self[:-1]:
        pretty_version += f"{str(row)}\n"
    # last one doesn't get a new line
    pretty_version += str(self[-1])
    return pretty_version

## Define a Matrix
In this section we'll focus on making things. First, we'll make a matrix A.

In [24]:
A = np.array([
    [0,0,0],
    [1,0,0],
    [1,1,0],
    [1,1,1]
    ])

print(pretty(A))

[0 0 0]
[1 0 0]
[1 1 0]
[1 1 1]


We can find out about the size of a matrix, by using the shape function. (A.shape would also work.)

In [15]:
np.shape(A)

(4, 3)

Now we'll make a vector called X. Remember, a vector is just an n x 1 matrix.

In [16]:
X = np.array([
    [1],
    [3]
    ])

print(pretty(X))

[1]
[3]


This makes another matrix called B and another one called C

In [30]:
B = np.array([
    [-4,-10],
    [3,7]
    ])

C = np.array([
    [1,2],
    [3,4]
    ])

print(f'B = \n{pretty(B)}')
print(f'C = \n{pretty(C)}')

B = 
[ -4 -10]
[3 7]
C = 
[1 2]
[3 4]


## Operations

To multiply by a scalar,

In [27]:
print(f'2*A = \n{pretty(2*A)}')

2*A = 
[0 0 0]
[2 0 0]
[2 2 0]
[2 2 2]


To add,

In [32]:
print(f"B+C is\n {pretty(B+C)}")

B+C is
 [-3 -8]
[ 6 11]


To multiply,

In [34]:
D = np.dot(B,C)
print(pretty(D))

[-34 -48]
[24 34]


Be careful, B*B works, but isn't the usual matrix multiplication, it's a thing called the Hadamard product. (https://en.wikipedia.org/wiki/Hadamard_product_(matrices))

To calculate the determinant,

In [37]:
print(np.linalg.det(B))

2.0


To calculate an inverse matrix

In [39]:
print(f'B inverse is \n{pretty(np.linalg.inv(B))}')

B inverse is 
[3.5 5. ]
[-1.5 -2. ]


To transpose

In [40]:
print(f"A transpose is:\n{pretty(np.transpose(A))}")

A transpose is:
[0 1 1 1]
[0 0 1 1]
[0 0 0 1]


To calculate a power, you can't use the usual power operator from python, because it'll do the Hadamard product again.

In [42]:
print(f"B^2 = \n {np.dot(B,B)}")
print(f"B^3 = \n {np.dot(B, np.dot(B,B))}")

B^2 = 
 [[-14 -30]
 [  9  19]]
B^3 = 
 [[-34 -70]
 [ 21  43]]


## Eigenpairs

In [22]:
eigenvalues = np.linalg.eig(B)[0]
eigenvectors = np.linalg.eig(B)[1]

for i in range(len(eigenvalues)):
    print(f'({eigenvalues[i]}, {eigenvectors[i]})')

(0.9999999999999964, [-0.89442719  0.85749293])
(2.0000000000000036, [ 0.4472136  -0.51449576])
